name: localizx
description: "The easiest and most light localization package"
version: 0.0.1
homepage: https://swypex.com

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  analyzer: ^10.0.0
  universal_io: ^2.3.1
  async: ^2.13.0
  build: ^4.0.4
  code_builder: ^4.11.1
  dart_style: ^3.1.5
  glob: ^2.1.3
  source_gen: ^4.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

